In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"D:\Machine learning dataset\CarPrice.csv")
data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [4]:
data.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [5]:
data["fueltype"].unique()

array(['gas', 'diesel'], dtype=object)

In [6]:
data["fueltype"]=data["fueltype"].map({"gas":1,"diesel":0})

In [7]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data["carbody"]=l1.fit_transform(data["carbody"])
data["carbody"].value_counts()

3    96
2    70
4    25
1     8
0     6
Name: carbody, dtype: int64

In [8]:
data["enginetype"]=l1.fit_transform(data["enginetype"])
data["enginetype"].value_counts()

3    148
4     15
5     13
2     12
0     12
6      4
1      1
Name: enginetype, dtype: int64

In [9]:
data

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,1,std,two,0,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,1,std,two,0,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,1,std,two,2,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,1,std,four,3,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,1,std,four,3,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),1,std,four,3,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,1,turbo,four,3,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,1,std,four,3,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,0,turbo,four,3,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,1,turbo,four,3,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [10]:
x =data.iloc[:,[3,6,10,11,12,14,16]]
y =data.iloc[:,-1]
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [12]:
x_test

     fueltype  carbody  carlength  carwidth  carheight  enginetype  enginesize
52          1        2      159.1      64.2       54.1           3          91
181         1        4      187.8      66.5       54.1           0         161
5           1        3      177.3      66.3       53.1           3         136
18          1        2      141.1      60.3       53.2           2          61
188         1        3      171.7      65.5       55.7           3         109
170         1        1      176.2      65.6       52.0           3         146
76          1        2      157.3      64.4       50.8           3          92
154         1        4      169.7      63.6       59.1           3          92
104         1        2      170.7      67.9       49.7           5         181
33          1        2      150.0      64.0       52.6           3          92
12          1        3      176.8      64.8       54.3           3         164
129         1        2      175.7      72.3       50.5           1         203
55          1        2      169.0      65.7       49.6           6          70
66          0        3      175.0      66.1       54.4           3         134
45          1        3      155.9      63.6       52.0           3          90
169         1        2      176.2      65.6       52.0           3         146
130         1        4      181.5      66.5       55.2           3         132
7           1        4      192.7      71.4       55.7           3         136
37          1        2      167.5      65.2       53.3           3         110
152         1        2      158.7      63.6       54.5           3          92
80          1        2      173.0      65.4       49.4           3         110
111         1        3      186.7      68.4       56.7           2         120
131         1        2      176.8      66.6       50.5           3         132
171         1        2      176.2      65.6       52.0           3         146
179         1        2      183.5      67.7       52.0           0         171
138         1        2      156.9      63.4       53.7           4          97
156         1        3      166.3      64.4       53.0           3          98
113         1        4      198.9      68.4       56.7           2         120
161         1        2      166.3      64.4       52.8           3          98
89          1        3      165.3      63.8       54.5           3          97
183         1        3      171.7      65.5       55.7           3         109
193         1        4      183.1      66.9       55.1           3         109
125         1        2      168.9      68.3       50.2           3         151
173         1        3      175.6      66.5       54.9           3         122
92          1        3      165.3      63.8       54.5           3          97
16          1        3      193.8      67.9       53.7           3         209
189         1        0      159.3      64.2       55.6           3         109
136         1        2      186.6      66.5       56.1           0         121
22          1        2      157.3      63.8       50.8           3          90
74          1        1      199.2      72.0       55.4           5         304
44          1        3      155.9      63.6       52.0           3          90

In [13]:
y_test

52      6795.0
181    15750.0
5      15250.0
18      5151.0
188     9995.0
170    11199.0
76      5389.0
154     7898.0
104    17199.0
33      6529.0
12     20970.0
129    31400.5
55     10945.0
66     18344.0
45      8916.5
169     9989.0
130     9295.0
7      18920.0
37      7895.0
152     6488.0
80      9959.0
111    15580.0
131     9895.0
171    11549.0
179    15998.0
138     5118.0
156     6938.0
113    16695.0
161     8358.0
89      5499.0
183     7975.0
193    12290.0
125    22018.0
173     8948.0
92      6849.0
16     41315.0
189    11595.0
136    18150.0
22      6377.0
74     45400.0
44      8916.5
Name: price, dtype: float64

In [14]:
from sklearn.linear_model import LinearRegression
regressor =LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred =regressor.predict(x_test)
print(y_pred)

[ 7556.81403286 15868.24621343 14213.82618612  -764.2376408
 10423.72986143 17336.01809336  7190.53973159  5902.28469082
 21910.10746696  6708.46844279 16487.9115755  27337.84765776
  7076.31097943 13729.60028977  5032.95997469 15960.89595529
 13126.38858336 18377.92746133 11023.1623796   7226.15648619
 10888.6152915  14882.68578086 14902.92105102 15960.89595529
 20183.65742188  7723.87613657  7442.10052215 14257.44390894
  8784.6030546   7015.74581355 10423.72986143 10795.77781685
 18021.08976409 12898.80612153  7015.74581355 25328.89859243
 12708.0291898  14106.41512108  6461.89075866 43968.7605619
  5032.95997469]

In [16]:
x_test

     fueltype  carbody  carlength  carwidth  carheight  enginetype  enginesize
52          1        2      159.1      64.2       54.1           3          91
181         1        4      187.8      66.5       54.1           0         161
5           1        3      177.3      66.3       53.1           3         136
18          1        2      141.1      60.3       53.2           2          61
188         1        3      171.7      65.5       55.7           3         109
170         1        1      176.2      65.6       52.0           3         146
76          1        2      157.3      64.4       50.8           3          92
154         1        4      169.7      63.6       59.1           3          92
104         1        2      170.7      67.9       49.7           5         181
33          1        2      150.0      64.0       52.6           3          92
12          1        3      176.8      64.8       54.3           3         164
129         1        2      175.7      72.3       50.5           1         203
55          1        2      169.0      65.7       49.6           6          70
66          0        3      175.0      66.1       54.4           3         134
45          1        3      155.9      63.6       52.0           3          90
169         1        2      176.2      65.6       52.0           3         146
130         1        4      181.5      66.5       55.2           3         132
7           1        4      192.7      71.4       55.7           3         136
37          1        2      167.5      65.2       53.3           3         110
152         1        2      158.7      63.6       54.5           3          92
80          1        2      173.0      65.4       49.4           3         110
111         1        3      186.7      68.4       56.7           2         120
131         1        2      176.8      66.6       50.5           3         132
171         1        2      176.2      65.6       52.0           3         146
179         1        2      183.5      67.7       52.0           0         171
138         1        2      156.9      63.4       53.7           4          97
156         1        3      166.3      64.4       53.0           3          98
113         1        4      198.9      68.4       56.7           2         120
161         1        2      166.3      64.4       52.8           3          98
89          1        3      165.3      63.8       54.5           3          97
183         1        3      171.7      65.5       55.7           3         109
193         1        4      183.1      66.9       55.1           3         109
125         1        2      168.9      68.3       50.2           3         151
173         1        3      175.6      66.5       54.9           3         122
92          1        3      165.3      63.8       54.5           3          97
16          1        3      193.8      67.9       53.7           3         209
189         1        0      159.3      64.2       55.6           3         109
136         1        2      186.6      66.5       56.1           0         121
22          1        2      157.3      63.8       50.8           3          90
74          1        1      199.2      72.0       55.4           5         304
44          1        3      155.9      63.6       52.0           3          90

In [17]:
ab=regressor.score(x_test,y_test)*100
ab

79.14762043362047